name 'unbork_ohai_rpm_plugin'
maintainer 'Richard Nixon'
maintainer_email 'richard.nixon@btinternet.com'
license 'All Rights Reserved'
description 'Unborks the OHAI RPM plugin'
version '0.1.0'
chef_version '>= 16.0'

issues_url 'https://github.com/trickyearlobe/unbork_ohai_rpm_plugin/issues'
source_url 'https://github.com/trickyearlobe/unbork_ohai_rpm_plugin'
